name: Run Maccabi TLV Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Restore cache (sent_articles.txt)
        uses: actions/cache@v4
        with:
          path: sent_articles.txt
          key: sent-articles-cache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Save updated sent_articles.txt to cache
        uses: actions/cache@v4
        with:
          path: sent_articles.txt
          key: sent-articles-cache
      - name: Commit sent.json updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --no-rebase
          git add sent.json
          git commit -m "Update sent.json with new articles" || echo "No changes to commit"
          git push

